### ISSUE TITLE
TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

### ISSUE THREAD

**Issue by DawnDoe** [iliaschalkidis/ELMo-keras#1]
Hi, I test the elmo code and encounter building errors.
Could you post the requirements, specifically the tf and keras version ?

**Comment by iliaschalkidis** [comment]
The function `while_loop()` is called via `tf.map_fn()` and includes the parameter `maximum_iterations`. I suspect a version inconsistency, as you also imply. I suggest upgrading to keras 2.2.4 and tensorflow 1.5+. But you should better upgrade into tensorflow 1.12 if this is not a restriction for you.

Please let me know if there are further issues or upgrading the libraries solved the issue.

**Comment by DawnDoe** [comment]
Tensorflow-gpu==1.12 and keras==2.2.4 works with no exception.  Thank you very much.

There are other issues when training with parameter 'token_encoding'=='char' in the model.  Perhaps you did not test it fully. Maybe next_ids and previous_ids dtype should be checked.

**Comment by iliaschalkidis** [comment]
I forgot to check that the last time I updated the code base for full softmax support on evaluation mode...
