### ISSUE TITLE
some problem about the get_outputs() function

### ISSUE THREAD

**Issue by Adherer** [iliaschalkidis/ELMo-keras#10]
As the param state: 'last' for 2nd LSTMs outputs,
but in your function, this is:
```python
if state == 'last':
            elmo_vectors = preds[0]
```
however, I think if we want to return the 2nd LSTMs outputs, the code is:
```python
if state == 'last':
            elmo_vectors = preds[-1]
```
I hope that you can answer my doubts, I will be grateful.

**Comment by iliaschalkidis** [comment]
@Adherer that's true. Thanx for mentioning this bug!
