### ISSUE TITLE
MemoryError during evaluation

### ISSUE THREAD

**Issue by lupo112** [iliaschalkidis/ELMo-keras#4]
Hi

I am having some problems in evaluation of trained model. I think the perplexity algorithm is not memory efficient. What hardware did you use?

I was trying to evaluate on PC with 32GB RAM and NVidia 1080TI 11GB.
In second test I wat trying to evaluate trained model on compute server with 64GB RAM and 3x NVidia 1080TI 11GB.
On both cases, I am getting MemoryError on evaluation step.

Any idea, how to evaluate and compute perplexity of trained model?

**Comment by iliaschalkidis** [comment]
Hi @lupo112, sorry for being late!

Probably using the generator in a more memory-efficient way will do the trick. So far, the `evaluate()` function does not use the generator (`test_data`) in a lazy-loading fashion as in training with `fit_generator()`. Instead, it precomputes everything around `test_data` and that's the biggest issue. 

In your case, I would try to load `test_data` and call predict function batch by batch and collect just `y` and `predictions`, then compute perplexity on top of them. This means someone needs to refactor 208-222 lines on model.py.
