### ISSUE TITLE
How to use Elmo Embeddings (Word Vectors, Sentence Vectors)

### ISSUE THREAD

**Issue by shleo** [iliaschalkidis/ELMo-keras#6]
Hi,
Great work! But I am wondering how to use the weight files after training. For example, how could I  turn a sentence into a vector.

Best

**Comment by iliaschalkidis** [comment]
Hi @shleo,

I just added a new functionality, where given a trained model, you can retrieve output vectors (ELMo embeddings) for downstream tasks (e.g., NER, Text Classification, etc.).

```
# Init ELMo
elmo_model = ELMo(parameters)

# Load ELMo encoder
elmo_model.load_elmo_encoder()

# Get ELMo embeddings to feed as inputs for downstream tasks
elmo_embeddings = elmo_model.get_outputs(test_generator, output_type='words', state='mean')

# BUILD & TRAIN NEW KERAS MODEL FOR DOWNSTREAM TASK (E.G., TEXT CLASSIFICATION)
```

I added a few options:

- `output_type`: you can either retrieve word vectors or sentence vectors
- `state`: the vectors are either based on last hidden layer (2nd LSTMs) or they are produced as a mean over inputs, 1st LSTMs and 2nd LSTMs

I wish this will help you further on!

**Comment by shleo** [comment]
Hi Ilias,
This solved my problem, Thanks!
Best

**Comment by desktoop** [comment]
I found there are 4358 lines in wiki.test.token file, but elmo_embedding's length is 2179. The number of lines in wiki.test.token is always two times of the elmo_embedding's length. Why are they different?
