### ISSUE TITLE
Is there a bug in lm_generator.py

### ISSUE THREAD

**Issue by alsm168** [iliaschalkidis/ELMo-keras#7]
hello, when I test the code of test_generator.py,I find a bug in get_token_char_indices() of lm_generator.py 
in line 132:
'if token_ids[1]'  should changed to 'if token_ids[1].any()'?

**Comment by iliaschalkidis** [comment]
Hi @alsm168,

I'm trying to remember why this line even exists... 😄 

It could be `token_ids[1].any()` or most probably `sum(token_ids[1])` but right now, I'm missing the semantics of this if-clause (why we need to check if the char-indices array has been filled in 1st position?)... Any idea? 

It's like I'm checking if there is any word at all in this line or it's empty... I cannot find any other probable cause that `token_ids[1]` would not be overridden from 0, its initialization value in case of word-level LM, to any other index; or 0s to char indices, in case of char-level LM. Probably I faced this issue in the demo dataset and had to bypass somehow....

**Comment by alsm168** [comment]
Hi, thanks for your reply. I have got the idea of the meaning of the if-clause.😄
